from __future__ import annotations

from collections import OrderedDict
from dataclasses import dataclass
import re
import secrets
import threading
import time
from typing import Callable, Generic, TypeVar


T = TypeVar("T")


@dataclass
class _SessionEntry(Generic[T]):
    value: T
    touched_at: float


class SessionStore(Generic[T]):
    """Thread-safe bounded in-memory session store with idle TTL.

    This prevents conversation memory from being shared across customers.
    For multi-process production deployment, replace this with Redis or
    another shared session backend.
    """

    def __init__(
        self,
        factory: Callable[[], T],
        *,
        ttl_seconds: int = 3600,
        max_sessions: int = 500,
    ):
        self.factory = factory
        self.ttl_seconds = max(60, int(ttl_seconds))
        self.max_sessions = max(1, int(max_sessions))
        self._items: OrderedDict[str, _SessionEntry[T]] = OrderedDict()
        self._lock = threading.RLock()

    def get_or_create(
        self,
        session_id: str | None = None,
    ) -> tuple[str, T]:
        now = time.monotonic()

        with self._lock:
            self._evict_expired(now)

            normalized = self._normalize_session_id(session_id)

            if normalized and normalized in self._items:
                entry = self._items.pop(normalized)
                entry.touched_at = now
                self._items[normalized] = entry
                return normalized, entry.value

            new_id = normalized or secrets.token_urlsafe(
                24
            )
            value = self.factory()
            self._items[new_id] = _SessionEntry(
                value=value,
                touched_at=now,
            )

            while len(self._items) > self.max_sessions:
                self._items.popitem(last=False)

            return new_id, value

    def remove(self, session_id: str) -> None:
        with self._lock:
            self._items.pop(session_id, None)

    def __len__(self) -> int:
        with self._lock:
            self._evict_expired(time.monotonic())
            return len(self._items)

    def _evict_expired(self, now: float) -> None:
        expired = [
            session_id
            for session_id, entry in self._items.items()
            if (now - entry.touched_at) > self.ttl_seconds
        ]

        for session_id in expired:
            self._items.pop(session_id, None)

    def _normalize_session_id(
        self,
        session_id: str | None,
    ) -> str | None:
        if not isinstance(session_id, str):
            return None

        value = session_id.strip()
        if not value:
            return None

        # Accept only opaque IDs with enough entropy/length. This blocks
        # accidental session fixation with values such as "customer1" and
        # keeps IDs conservative for logs/storage keys. Legacy 32-char hex
        # IDs generated by the previous build remain valid.
        if not re.fullmatch(
            r"[A-Za-z0-9_-]{20,128}",
            value,
        ):
            return None

        return value
